# Check https://github.com/purple52/librarian-puppet-vagrant for the 
# original idea of installing Puppet Modules with librarian during the shell
# provisioning phase

forge "http://forge.puppetlabs.com"

# This modules will be available during the VM provisioning

# Installed from Forge
#mod "puppetlabs/vcsrepo"
#mod "puppetlabs/firewall"
mod "puppetlabs/stdlib"

# Installed from private Git repo
mod "my-mod",
   :git => "https://url/to/my/module/repo.git"
